### PR TITLE
fixup PR #600

### PR DESCRIPTION
**Pull request by calid**
* Restore non-C# changes lost when #600 was integrated
* Re-integrate just the desired C# changes from #600 

@chubbson can you review the C# examples make sure they're in the desired state?

ref: http://lists.zeromq.org/pipermail/zeromq-dev/2015-December/029903.html

### CODE REVIEW

**Comment by calid** [comment]
@hintjens everything seems restored correctly, the only one I'm unsure of is `chapter2.txt`  The language seems flipped and I'm not sure it's correct.  Can you take a look and let me know what you think?  I can't seem to find the corresponding commit that originally flipped the language.

**Comment by calid** [comment]
Nevermind, I found it: c076f1ef8694cc37dc256a9038ea1437392b6452

So it was restored correctly, is this an unrelated typo?

> The proxy has to forward these subscription messages **from subscriber side to publisher side**, by reading them **from the XPUB socket and writing them to the XSUB socket**

"from subscriber to publisher" and "from XPUB to XSUB" seems mismatched.

**Comment by chubbson** [comment]
c# samples are in desired state, compiled and checked them

**Comment by calid** [comment]
awesome, thanks

**Comment by metadings** [comment]
I don't have your examples, when I'm doing `git pull zeromq master` where `git remote -v` is

	zeromq	https://github.com/imatix/zguide/ (fetch)
	zeromq	https://github.com/imatix/zguide/ (push)

**Comment by calid** [comment]
@metadings I'm not sure what you mean, I have tripping.cs when I pull master and it's the same as pre-600?

```
calid@arch /tmp
[✔]▶ git clone https://github.com/imatix/zguide.git
Cloning into 'zguide'...
remote: Counting objects: 24183, done.
remote: Total 24183 (delta 0), reused 0 (delta 0), pack-reused 24183
Receiving objects: 100% (24183/24183), 49.50 MiB | 6.74 MiB/s, done.
Resolving deltas: 100% (16689/16689), done.
Checking connectivity... done.

calid@arch /tmp
[✔]▶ cd zguide/

calid@arch (master[v2.2-1093]=) /tmp/zguide
[✔]▶ ls examples/C#/tripping.cs
examples/C#/tripping.cs

calid@arch (master[v2.2-1093]=) /tmp/zguide
[✔]▶ git show --pretty=short d8b4d46015c30
commit d8b4d46015c30e99c23faf82d3ffc0c4f539861b
Merge: 7e2c6de a69b446
Author: Pieter Hintjens <ph@imatix.com>

    Merge pull request #600 from chubbson/master

calid@arch (master[v2.2-1093]=) /tmp/zguide
[✔]⚑ git diff d8b4d46015c30e99c23faf82d3ffc0c4f539861b~ -- tripping.cs

calid@arch (master[v2.2-1093]=) /tmp/zguide
[✔]▶ # no diffs, same as it always was

```

**Comment by calid** [comment]
And as far as changes introduced by #600, it seems like those were preserved in 3c6b156?

```
calid@arch (master[v2.2-1093]=) /tmp/zguide
[✔]▶ git log --oneline a69b446 -- examples/C#/tripping.cs
cf37ab4 cleanup tripping sample. it often crashes if more than 1000 or 10000 msg sent without receive it before. results in EAGAIN error. it depends on box resources. on my desktop pc it crashes after 8000-16000, on my laptop it crashes after 1600-7000.
40c0bfa Updateing C# Expamples: Added tripping
518807b Improved code blocks throughout text.
4000281 Added tripping example

calid@arch (master[v2.2-1093]=) /tmp/zguide
[✔]▶ git log --oneline master -- examples/C#/tripping.cs
3c6b156 recommit #600 C# changes
518807b Improved code blocks throughout text.
4000281 Added tripping example

calid@arch (master[v2.2-1093]=) /tmp/zguide
[✔]⚑ git diff master:examples/C#/tripping.cs a69b446:examples/C#/tripping.cs
```

**Comment by metadings** [comment]
Ya, looks okay for now...

**Pull request merged**
