### PR TITLE
Fixes #1787

### PR DESCRIPTION
**Pull request by UsamaMehboob**

### CODE REVIEW

**Comment by hintjens** [comment]
Thanks :)

**Comment by hitstergtd** [comment]
@hintjens,

Just checked C, C# and Ruby examples, and I think they suffer the same issue. Also, the online guide doesn't seem to have updated, or am I missing something?

**Comment by hintjens** [comment]
I will update the online text, it's a process I need to run manually.

**Comment by hitstergtd** [comment]
@hintjens,
OK. Shall I send a Pull for the C, C# and Ruby examples?

**Comment by hintjens** [comment]
Yes, sure. And if you want me to update the online text let me know. I could eventually do this via Travis but there are API keys and such involved and I'm not enthused by automating that.

**Comment by hitstergtd** [comment]
OK, I will sort out the Pull momentarily. I would be more than happy to update the online text, if you can sort out the requisite access-fu; if that's what you meant by it. Agree re. Travis-CI and keys.

**Comment by metadings** [comment]
This is wrong, I need to revert this.

- You can't `frontend.connect("tcp://*:5557");` just because of the address `*`.

1. Usually PathoPub is binding PUB to 5556, PathoSub is connecting to SUB on 5556.

2. Using LVCache, which is binding SUB to 5557, and XPUB to 5558,
Now you can use PathoPub, to connect to XPUB on 5558,
and PathoSub, to connect to SUB on 5557.

**Comment by hintjens** [comment]
Don't revert @metadings, just send a patch to fix it. Thanks :)

**Pull request merged**
