### PR TITLE
Adding FLCliApi.FreelanceClient class!

### PR DESCRIPTION
**Pull request by metadings**
Have a look at the code: [FLCliApi](https://github.com/metadings/zguide/blob/master/examples/C%23/flcliapi.cs), [FLClient3](https://github.com/metadings/zguide/blob/master/examples/C%23/flclient3.cs), [FLServer3](https://github.com/metadings/zguide/blob/master/examples/C%23/flserver3.cs) !

### CODE REVIEW

**Comment by metadings** [comment]
Something personal: Do you like to be named in "Authors: Pieter Hintjens, Uli Riehm" or do you think this is not appropriate?

**Comment by hintjens** [comment]
In the code? You can just use your own name :-)

**Comment by metadings** [comment]
Well I thought you are the author of the C examples, so I don't know...

**Comment by hintjens** [comment]
:-) well, the author tells people who to ask for help when they can't use
the examples... so it should be you.

**Comment by metadings** [comment]
Ok ;-)

**Pull request merged**
